### ISSUE TITLE
Update PyPI package

### ISSUE THREAD

**Issue by mak448a** [ItsCEED/Imaginepy#11]
The PyPI package that was released May 22 doesn't have the latest fixes for #7. Please update the PyPI package. Thanks!

**Comment by ItsCEED** [comment]
I think this will need more things before pypi is updated, please just use the repo for now

**Comment by mak448a** [comment]
Okay, thanks

**Comment by ItsCEED** [comment]
Updated, and all should be good now.

**Comment by mak448a** [comment]
Thanks!
