### ISSUE TITLE
You need to fix your models and styles like this.

### ISSUE THREAD

**Issue by raymerjacque** [ItsCEED/Imaginepy#15]
Currently your script only processes styles, no models. the Imagine.art project works on both models and styles.

its meant to process [selected model]+[user prompt]+[style]

but right now everyone is processing it only [user prompt]+[style]

i have corrected the issue in my python version https://github.com/raymerjacque/vyro-imagine-ai

i suggest you take a look and update your script. this new method greatly improves the quality of images generated and is more inline with the website and mobile app.

i have also made a video detailing what i changed and why. see the video below.

https://youtu.be/N2Hy8BauaBc

**Comment by ItsCEED** [comment]
The mobile app and the web have them as we have in this version here.
I see no reason to reshuffle the code as we won't last for long...

**Comment by ItsCEED** [comment]
nevermind, ignor the last comment, update is on the way.

**Comment by ItsCEED** [comment]
Updated pushed.
