### ISSUE TITLE
An error occurred while making the request: 400

### ISSUE THREAD

**Issue by nxkiss** [ItsCEED/Imaginepy#16]
Every time i try to generate images using your sample code i get following error:

"An error occurred while making the request: 400 Client Error: Bad Request for url: https://inferenceengine.vyro.ai/sdprem
An error occurred while generating the image."

I had this script running properly on my server for a montho now but suddenly it broke. Is this patched now? 
Also adding a style to Imagine() breaks.
imagine = Imagine(style=Style.ANIME)

-> TypeError: Imagine.__init__() got an unexpected keyword argument 'style'

**Comment by ItsCEED** [comment]
You installed from pypi?
If yes, install from the repo directly

**Comment by ItsCEED** [comment]
You can update from pypi now.
Please read the changes.
