### ISSUE TITLE
pull request

### ISSUE THREAD

**Issue by raymerjacque** [ItsCEED/Imaginepy#21]
i want to create a pull request, but the only branch it shows is "main". i do not see any other branches available for pull request. i tried many ways, it only shows 1 branch.

I have been working hard on this GUI, it looks great, works great and supports all the functions and features. 

1. it has user input, model selection box, style selection box, ratio selection box, a cf slider, a negative word user input box. a generate button and a browse button.
2. it supports both linux and windows.
3. it has an image preview that scales according to ratio selected. if the generated image is clicked with mouse, it opens the image in the default image viewer.
4. if the browse button is clicked it opens the image folder.
5. generated images are saved in png format and saved with a random name so as to not overwrite previous saved images.
6. its directly compatible with your code out of the box. simply start the .py file and it works.

here is a screenshot.

on linux : https://freeimage.host/i/HPiZ7Wl

on windows : https://freeimage.host/i/HPit9Ll

**Comment by mak448a** [comment]
You need to commit your changes to a different branch that you created, and then submit a pull request.
Also, nice app! I would recommend changing the filename, though. Maybe change it from `generate.py` to `gui.py`.

**Comment by raymerjacque** [comment]
i have tried, it says there is only one branch. i also noticed the other merges are all listed as "main"... i tried to fork again, i even unticked main, it still forks main. 

o well... i tried to contribute, guess its not meant to be. ill keep working on the gui for myself. i just added some new features. next im adding sharing options, so you can share images to social media with a simply click.

**Comment by mak448a** [comment]
You have to create a branch.

**Comment by mak448a** [comment]
I think you have to do something like
```shell
git branch development-test
``` 

or something like that

**Comment by raymerjacque** [comment]
ok i think i figured it out. ill send a pull request again

**Comment by mak448a** [comment]
Close this issue if you've solved the pull request issue, please.
