### ISSUE TITLE
Controlnet isn't working and giving an internal server error 500

### ISSUE THREAD

**Issue by VanshShah1** [ItsCEED/Imaginepy#4]
from imaginepy import Control, Style, Imagine, Ratio
import string
import random

imagine = Imagine()
res = ''.join(random.choices(string.ascii_lowercase + string.digits, k=5))
stres = str(res) 
img_data = imagine.controlnet(image="0jx68.png", prompt="robot walking in the rain", style=Style.IMAGINE_V4_Beta, control=Control.SCRIBBLE)
img_data = imagine.upscale(image=img_data)
try:
    with open(f"{stres}.png", mode="wb") as img_file:
        img_file.write(img_data)
except Exception as e:
        print(f"An error occurred while writing the image to file: {e}")

**Comment by ItsCEED** [comment]
#9

**Comment by ItsCEED** [comment]
All should be good now.
